services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: True
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn index:app --host 0.0.0.0 --port $PORT
